version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
